name: Build and Release

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' 

    - name: Install dependencies
      run: yarn install

    - name: Build project
      run: yarn build

    - name: Prepare releases
      run: |
        cd dist
        for dir in */ ; do
          zip -r "${dir%/}.zip" "$dir"
        done
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/*.zip"
